apiVersion: apps/v1
kind: Deployment
metadata:
  name: clip-gke
spec:
  selector:
    matchLabels:
      app: clip-gke
  template:
    metadata:
      labels:
        app: clip-gke
    spec:
      containers:
        - name: clip-gke
          image:  us-central1-docker.pkg.dev/linen-patrol-428513-u3/my-repo/portfolio:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: clip-service
spec:
  type: LoadBalancer
  selector:
    app: clip-gke
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
